# Generated by Django 5.1.1 on 2024-09-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_taks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taks',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
